apiVersion: v1
kind: Namespace
metadata:
  name: curso-kubernetes

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: curso-kubernetes
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root1234

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-windows
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-windows-hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/c/k8s/mysql-data
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: curso-kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-windows-hostpath
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-pvc
  namespace: curso-kubernetes
spec:
  type: ClusterIP
  selector:
    app: mysql-pvc
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: curso-kubernetes
spec:
  serviceName: mysql-service-pvc
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pvc
  template:
    metadata:
      labels:
        app: mysql-pvc
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: curso_kubernetes
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc