global:
  security:
    allowInsecureImages: true

image:
  registry: public.ecr.aws
  repository: bitnami/mysql
  tag: 8.4

architecture: replication

auth:
  rootPassword: "rootpassword"
  database: "my_database"
  replicationUser: "replicator"
  replicationPassword: "replicatorpassword"

primary:
  persistence:
    enabled: true
    size: 8Gi

secondary:
  replicaCount: 2
  persistence:
    enabled: true
    size: 8Gi